[package]
name = "meesign-server"
version = "0.1.0"
edition = "2018"

[dependencies]
tonic = "0.6"
prost = "0.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "time"] }
uuid = { version = "1.0.0-alpha.1", features = ["v4", "fast-rng"] }
log = "0.4.16"
env_logger = "0.9.0"
hex = "0.4.3"
clap = { version = "3.1.8", features = ["derive"] }
rand = "0.8.5"

[build-dependencies]
tonic-build = "0.6"
