[package]
name = "meesign-server"
version = "0.1.0"
edition = "2018"

[dependencies]
tonic = "0.6"
prost = "0.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.0.0-alpha.1", features = ["v4", "fast-rng"] }

[build-dependencies]
tonic-build = "0.6"
