[package]
name = "meesign-server"
version = "0.2.0"
edition = "2018"

[dependencies]
tonic = { version = "0.9.0", features = ["transport", "tls"] }
prost = "0.11.0"
tokio = { version = "1.24", features = ["macros", "rt-multi-thread", "time", "fs"] }
tokio-stream = "0.1.10"
uuid = { version = "1.0.0-alpha.1", features = ["v4", "fast-rng"] }
log = "0.4.16"
env_logger = "0.9.0"
hex = "0.4.3"
clap = { version = "3.1.8", features = ["derive"] }
rand = "0.8.5"
tempfile = "3.3.0"
lazy_static = "1.4.0"
openssl = "0.10.55"
sha2 = "0.10.6"
meesign-crypto = { git = "https://github.com/crocs-muni/meesign-crypto", rev = "08ca33a" }

[build-dependencies]
tonic-build = "0.8.2"

[features]
default = ["cli"]
cli = []
