# Build meesign helper
FROM maven:3-jdk-11 as java-builder
WORKDIR /
RUN git clone https://github.com/dufkan/meesign-helper.git meesign-helper
RUN cd meesign-helper && mvn clean compile assembly:single


# Build and statically link the meesign binary
FROM messense/rust-musl-cross:aarch64-musl as rust-builder
# Install protobuf compiler
RUN echo "${PATH}"
ENV PATH="${PATH}:/usr/local/bin"
RUN echo "${PATH}"
RUN curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-aarch_64.zip" && \
    unzip ./protoc-21.12-linux-aarch_64.zip -d /usr/local && \
    rm -rf ./protoc-21.12-linux-aarch_64.zip && \
    /usr/local/bin/protoc && \
    protoc --version

WORKDIR /home/builder/src
ADD . .
RUN cargo build --release --target aarch64-unknown-linux-musl


# Use a clean container to run the binary 
# note it must be a JRE image for meesign helper
FROM eclipse-temurin:11-jre-jammy as runner

# Set specific UID and GID so the meesign user is compatible with the owner UID of the mapped key volume
RUN addgroup --system meesign --gid 1000 && adduser --uid 1000 --system meesign --ingroup meesign
USER meesign

COPY --chown=meesign:meesign --from=rust-builder /home/rust/src/target/x86_64-unknown-linux-musl/release/meesign-server /usr/local/bin/meesign-server
COPY --chown=meesign:meesign --from=java-builder /meesign-helper/target/signPDF-1.0-SNAPSHOT-jar-with-dependencies.jar /meesign/MeeSignHelper.jar

ARG SERVER_PORT=1337
ARG BUILD_DATE
ARG REVISION
ARG BUILD_VERSION

LABEL org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.source="https://github.com/crocs-muni/meesign-server" \
    org.opencontainers.image.version=${BUILD_VERSION} \
    org.opencontainers.image.revision=${REVISION} \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.title="meesign-server" \
    org.opencontainers.image.description="Meesign server for threshold ECDSA signatures." \
    org.opencontainers.image.vendor="CRoCS, FI MUNI" \
    org.label-schema.docker.cmd="docker run --detach --publish 1337:1337 --volume `pwd`/keys/:/meesign/keys/ crocsmuni/meesign:latest"

EXPOSE ${SERVER_PORT}
# running the binary from a specific directory as meesign helper requires 
# a certificate and a private key in the currect directory 
WORKDIR /meesign
ENTRYPOINT ["meesign-server"]
CMD ["--addr", "0.0.0.0"]
