name: Nightly release

on:  
  schedule:
    # every 5 minutes
    - cron: '*/20 * * * *'
jobs:
  build-n-release-docker-nightly:
    name: Docker nightly
    # Run only on the main repo, not forks
    uses: ./.github/workflows/docker-base.yml
    secrets: inherit
    with:
      dockerhub_username: kristianmika
      project_name: meesign
      docker_tags: |
        kristianmika/meesign:nightly
