# Builds a Docker image and publishes it onto Dockerhub
name: Docker Base

on:
  workflow_call:

    inputs:
      dockerhub_username:
        required: true
        type: string
      project_name:
        required: true
        type: string
      docker_tags:
        required: false
        type: string

    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-and-publish-image:
    name: Docker stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # sets the tag env variable
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Declare build variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=commit_hash::$(git rev-parse HEAD)"    
          echo "::set-output name=curr_date::$(date --rfc-3339=seconds)"
      - name: Set the version tag
        # If the workflow contains a tag, set a version docker tag in format "user/project:tag"
        id: version_tag
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: echo "::set-output name=version_tag::${{ inputs.dockerhub_username }}/${{ inputs.project_name}}:${{ steps.tag.outputs.tag }}"
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ steps.version_tag.outputs.version_tag }}
            ${{ inputs.docker_tags }}
          context: .
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.curr_date }}
            BUILD_VERSION=${{ steps.tag.outputs.tag }}
            REVISION=${{ steps.vars.outputs.commit_hash }}
