name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-n-release-docker-stable:
    needs: build
    name: Build and release a stable Docker image
    # only tagged versions
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      dockerhub_username: kristianmika
      project_name: meesign
      docker_tags: |
        kristianmika/meesign:latest
